version: 1.0.{build}

clone_folder: c:\gopath\src\github.com\scientificgo\fft

environment:
  GOPATH: c:\gopath

build_script:
- cmd: go build -i

test_script:
- cmd: go test ./... -v -race -coverprofile=coverage.txt -covermode=atomic -timeout 0
