os:
  - osx
  - linux

language: go

go:
  - 1.x
  - tip

env:
  global:
    CC_TEST_REPORTER_ID=a2619ddcaef9fe12ec272542654eb6f3ef45e7e2c0dc7177d1e251ae02a23af5

install:
  - mkdir -p $GOPATH/src/scientificgo.org
  - mv $GOPATH/src/github.com/scientificgo/fft $GOPATH/src/scientificgo.org/fft
  - cd $GOPATH/src/scientificgo.org/fft

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - go test ./... -v -race -coverprofile=coverage.txt -covermode=atomic -timeout 0

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
