os:
  - osx
  - linux

language: go

go:
  - 1.x
  - tip

install:
  - go get -t -v ./...
  - go build
  
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - go test ./... -v -race -coverprofile=coverage.txt -covermode=atomic -timeout 0

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
